### ISSUE TITLE
crash DBAL < 2.5 on PHP7

### ISSUE THREAD

**Issue by metaclass-nl** [metaclass-nl/tresholds-governor#6]
Doctrine\DBAL\Query\QueryBuilder::andWhere assigns $this->getQueryPart('where') to its first argument variable. On PHP 7 this results in func_get_args(), which is called AFTERWARDS, to return the Doctrine\DBAL\Query\Expression\CompositeExpression from $this->getQueryPart('where') instead of the (string) argument supplied by \Metaclass\TresholdsGovernor\Gateway\DbalGateway::countWhereSpecifiedAfter.

Then the querybuilder adds the 'arguments' as extra AND expressions resulting in self-reference(s) from the CompositeExpression in $this->sqlParts['where'] (which is returned by $this->getQueryPart('where')). When the actual SQL string is being generated $this->sqlParts['where'] is casted to string resulting in an endless recursion. I guess that crashes PHP 7. 

This behavior is consistent with [a note in the php manual](http://php.net/manual/en/function.func-get-args.php):
```
If the arguments are passed by reference, any changes to the arguments 
will be reflected in the values returned by this function. 
As of PHP 7 the current values will also be returned if the arguments are passed by value."
```
The problem is solved in [this commit](https://github.com/doctrine/dbal/commit/75402954517d749df3705ef21d53c1e1709a6347#diff-305699f4a9180da213eb29c5671ab925) in dbal v2.5.0-BETA2 with comment:
```
HHVM compatibility: func_get_args

All func_get_args() calls have been moved to the top of the methods
because HHVM doesn't keep a copy of the original args for performance
reasons.
```

Tested on PHP7.0.1 windows VC14 x64 Non Thread Safe (2015-Dec-17 00:17:18) with Symfony v2.7.7, doctrine/dbal v2.4.4., metaclass-nl/authentication-guard-bundle  5ca9e55f744ead919ec9e630745010187f037652,  metaclass/tresholds-governor 9a74fae6f4e90c2aee18fcdc1cfa68d9dc6b1980

**Comment by gplanchat** [comment]
Same issue here on PHP 7.0.4 from homebrew and `doctrine/dbal` 2.4.x-dev (f5b85d182799c539d1a56aa145977aa2c43dfe1a) :

```
PHP 7.0.4 (cli) (built: Mar 25 2016 00:02:51) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

Symptoms are an infinite recursion in the `Doctrine\DBAL\Query\Expression\CompositeExpression`, the error isn't easy to detect.

For the report, everything was fixed after upgrading to version 2.5

**Comment by metaclass-nl** [comment]
To solve this by updating symfony one needs to update ones own composer.json to reflect the version numbers in the release of Syfony framework standard edition that is used before running composer update. IMHO the http://symfony.com/doc/current/cookbook/upgrade/minor_version.html should instruct one to allways do this instead of only mentioning it under "Dependency Errors" after "If this still doesn't work": debugging a crash like this is hard and even if one succeeds, finding that all that effort was only to find a "dependency error" is kind of frustrating.. )

**Comment by metaclass-nl** [comment]
Release v0.3 no longer uses DBAL's QueryBuilder, so it should also work on versions of DBAL < 2.5 with PHP 7, but this was not tested.
